# Generated by Django 3.2.12 on 2022-03-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_departament_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=180),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
