version: '3'

services:
  web:
    build: ./erm
    ports:
      - "8000:8000"
    volumes:
      - web-static:/static/
    command: /usr/local/bin/gunicorn erm.wsgi:application -w 2 -b :8000


volumes:
  web-static:
